name: Build and Push to Container Registry

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Branch
    - uses: actions/checkout@v3

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: trufflehog git file://. --since-commit HEAD --only-verified --fail
    # # Setting up Docker Builder
    # - name: Set up Docker Builder
    #   uses: docker/setup-buildx-action@v2

    
   