name: Build and Push to Container Registry

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Branch
    - uses: actions/checkout@v3

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        args: --entrypoint=
        run: |
          sh trufflehog filesystem . --exclude-paths trufflehog-excluded-paths.txt --fail --json --no-update > trufflehog-scan-result.json
    # # Setting up Docker Builder
    # - name: Set up Docker Builder
    #   uses: docker/setup-buildx-action@v2

    
   