name: Build and Push to Container Registry

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Branch
    # List files to debug
    - name: List workspace files
      run: ls -al ${{ github.workspace }}

    # Run TruffleHog inside Docker container
    - name: Secret Scanning with TruffleHog
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/workspace \
        -w /workspace \
        trufflesecurity/trufflehog:latest filesystem . \
        --exclude-paths /workspace/trufflehog-excluded-paths.txt \
        --fail --json --no-update > ${{ github.workspace }}/trufflehog-scan-result.json

    # Archive the TruffleHog JSON result as an artifact
    - name: Archive TruffleHog Scan Result
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-scan-result
        path: ./trufflehog-scan-result.json
    # - uses: actions/checkout@v3

    # - name: Secret Scanning
    #   uses: trufflesecurity/trufflehog@main
    #   with:
    #     args: --entrypoint=
    #     run: |
    #       sh trufflehog filesystem . --exclude-paths trufflehog-excluded-paths.txt --fail --json --no-update > trufflehog-scan-result.json

    # - name: Archive TruffleHog Scan Result
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: trufflehog-scan-result
    #     path: ./trufflehog-scan-result.json
    # # Setting up Docker Builder
    # - name: Set up Docker Builder
    #   uses: docker/setup-buildx-action@v2

    
   