name: Build and Push to Container Registry

on:
  push:
    branches: [master]

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    # Checkout Branch
    # List files to debug
    - name: Secret Scanning with TruffleHog
      run: |
        set +e  # Allow the script to continue even if TruffleHog fails
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          trufflesecurity/trufflehog:latest filesystem . \
          --exclude-paths trufflehog-excluded-paths.txt \
          --fail --json --no-update > ${{ github.workspace }}/trufflehog-scan-result.json
        set -e  # Re-enable the exit on error behavior

    # Archive the TruffleHog JSON result as an artifact
    - name: Archive TruffleHog Scan Result
      if: always()  # Ensure this step always runs
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-scan-result
        path: ${{ github.workspace }}/trufflehog-scan-result.json
    # - uses: actions/checkout@v3

    # - name: Secret Scanning
    #   uses: trufflesecurity/trufflehog@main
    #   with:
    #     args: --entrypoint=
    #     run: |
    #       sh trufflehog filesystem . --exclude-paths trufflehog-excluded-paths.txt --fail --json --no-update > trufflehog-scan-result.json

    # - name: Archive TruffleHog Scan Result
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: trufflehog-scan-result
    #     path: ./trufflehog-scan-result.json
    # # Setting up Docker Builder
    # - name: Set up Docker Builder
    #   uses: docker/setup-buildx-action@v2

    
   